version: '3'
services:
  vpnproxy:
    image: jataware/vpnproxy:dev
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    dns:
      - 1.1.1.1
      - 1.0.0.1
    networks:
      - default
    environment:
      - USERNAME=$NORDUSER
      - PASSWORD=$NORDPASS
      - PUSERNAME=$PIAUSER
      - PPASSWORD=$PIAPASS
      - WUSERNAME=$WINDUSER
      - WPASSWORD=$WINDPASS
      - LOCAL_NETWORK=192.168.1.0/24
    ports:
      - 8118:8118
      - 8080:8080
    restart: always

