version: '3'
services:
  vpnproxy:
    image: jataware/vpnproxy:dev
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    dns:
      - 8.8.8.8
    networks:
      - default
    environment:
      USERNAME: $NORDUSER
      PASSWORD: $NORDPASS
      PUSERNAME: $PIAUSER
      PPASSWORD: $PIAPASS
      WUSERNAME: $WINDUSER
      WPASSWORD: $WINDPASS
      LOCAL_NETWORK: 192.168.1.0/24
      LOCAL_NETWORKS:
      OVPN_DOWNLOAD_ON_START: ${OVPN_DOWNLOAD_ON_START:-"no"}
    ports:
      - 8118:8118
      - 8080:8080
    restart: always

