app:
  host: 0.0.0.0
  port: 8080

vpn_env:
  # my ip endpoint
  ip: https://5jr45codhg.execute-api.us-east-1.amazonaws.com/ip
  # directory of nord ovpn confs
  vpnconfigs: /etc/ovpn/configs
  # download ovpn configs on init
  reload_configs_on_startup: yes
  # openvpn conf
  vpnconfig: /etc/ovpn/openvpn.conf


wind:
  url: https://vpnrotate.s3.amazonaws.com/20210727_ovpn_tcp.zip
