app:
  host: 0.0.0.0
  port: 8080

vpn_env:
  # directory of nord ovpn confs
  vpnconfigs: /etc/ovpn/configs
  # download ovpn configs on init
  reload_configs_on_startup: yes
  # openvpn conf
  vpnconfig: /etc/ovpn/openvpn.conf


