#!/bin/sh

set -e
exec 2>&1

sleep 10

# Return traffic that went through OpenVPN works.
gw=$(ip route | awk '/default/ {print $3}')
ip route add to ${LOCAL_NETWORK} via $gw dev eth0

echo "extra networks: ${LOCAL_NETWORKS}"
for r in $(IFS=","; echo ${LOCAL_NETWORKS});
do
  echo "ip route add ${r}"
  ip route add to "${r}" via $gw dev eth0
done;

exec privoxy --no-daemon
