#!/bin/sh

set -e
exec 2>&1

sleep 10

# Return traffic that went through OpenVPN works.
gw=$(ip route | awk '/default/ {print $3}')
ip route add to ${LOCAL_NETWORK} via $gw dev eth0

exec privoxy --no-daemon
