#!/bin/sh


# assume load at least one VPN cred

if [ -n "$USERNAME" -a -n "$PASSWORD" ]; then
  echo "$USERNAME" > /etc/ovpn/nord.conf
  echo "$PASSWORD" >> /etc/ovpn/nord.conf
  chmod 600 /etc/ovpn/nord.conf
  
  echo "Loaded NordVPN credentials"
fi

if [ -n "$PUSERNAME" -a -n "$PPASSWORD" ]; then
  echo "$PUSERNAME" > /etc/ovpn/pia.conf
  echo "$PPASSWORD" >> /etc/ovpn/pia.conf
  chmod 600 /etc/ovpn/pia.conf

  echo "Loaded PIA credentials"
fi

if [ -n "$WUSERNAME" -a -n "$WPASSWORD" ]; then
  echo "$WUSERNAME" > /etc/ovpn/wind.conf
  echo "$WPASSWORD" >> /etc/ovpn/wind.conf
  echo "Loaded Windscribe credentials"
  chmod 600 /etc/ovpn/wind.conf
fi
