name: Docker Publish Version

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create docker container
      run: make docker_build
    - name: Push docker container
      env:
        GITLAB_PASS: ${{ secrets.GITLAB_PASS }}
        GITLAB_USER: ${{ secrets.GITLAB_USER }}
      run: make docker_publish prod=y
