name: Docker Image CI

on: [pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create docker container
      run: ./build-docker.sh
    - name: Run docker-compose
      run: docker-compose up -d
    - name: Check running containers
      run: docker ps -a
    - name: Run Tests
      run: ./run-tests.sh
    - name: Shutdown
      run: docker-compose down
